# <font color='red'>Data Indexing and Selection

# <font color='blue'>Data Selection in Series

In [1]:
# Series as dictionary

In [2]:
import pandas as pd

In [3]:
data = pd.Series([0.25,0.5,0.75,1.0], index = ['a','b','c','d'])

In [4]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [5]:
data['b']

0.5

In [6]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.items()

In [9]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [10]:
data['e'] = 1.25

In [11]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

## Series as one dimensional array

In [13]:
data # slicing by explicit index

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [14]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [15]:
data[0:2] # slicing by implicit integer index

a    0.25
b    0.50
dtype: float64

In [16]:
data[(data > 0.3) & (data < 0.8)] # masking

b    0.50
c    0.75
dtype: float64

In [17]:
data[['a','e']] # fancy indexing

a    0.25
e    1.25
dtype: float64

## Indexers: loc, iloc

In [18]:
data = pd.Series(['a','b','c'], index = [1,3,5])

In [19]:
data

1    a
3    b
5    c
dtype: object

In [20]:
# explicit index when indexing

In [21]:
data[1]

'a'

In [22]:
# implicit index when indexing

In [23]:
data[1:3]

3    b
5    c
dtype: object

In [24]:
# loc

In [25]:
data

1    a
3    b
5    c
dtype: object

In [26]:
data.loc[1]

'a'

In [27]:
data.loc[1:3]

1    a
3    b
dtype: object

In [28]:
# iloc

In [29]:
data

1    a
3    b
5    c
dtype: object

In [30]:
data.iloc[1]

'b'

In [31]:
data.iloc[1:3]

3    b
5    c
dtype: object

# <font color='blue'>Data Selection in DataFrame

## DataFrame as a dictionary

In [34]:
area = pd.Series({'California': 423967, 'Texas': 695662,
 'New York': 141297, 'Florida': 170312,
 'Illinois': 149995})

In [35]:
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127, 'Florida': 19552860,
 'Illinois': 12882135})

In [36]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [37]:
pop

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [38]:
data = pd.DataFrame({'area':area, 'pop':pop})

In [39]:
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [40]:
data['area'] # dictionary style

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [41]:
data['pop'] # dictionary style

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [42]:
data.area # attribute style

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [43]:
data.area is data['area']

True

In [44]:
data.pop is data['pop'] # Attribute calling is not safe

False

In [45]:
# Instead we go for always data['pop'] rather than data.pop

In [46]:
data['density'] = data['area'] / data['pop']

In [47]:
data

area       pop   density
California  423967  38332521  0.011060
Texas       695662  26448193  0.026303
New York    141297  19651127  0.007190
Florida     170312  19552860  0.008710
Illinois    149995  12882135  0.011644

## DataFrame as two-dimensional array

In [48]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 1.10602431e-02],
       [6.95662000e+05, 2.64481930e+07, 2.63028177e-02],
       [1.41297000e+05, 1.96511270e+07, 7.19027463e-03],
       [1.70312000e+05, 1.95528600e+07, 8.71033700e-03],
       [1.49995000e+05, 1.28821350e+07, 1.16436445e-02]])

In [49]:
data.T # swap rows and columns

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  1.106024e-02  2.630282e-02  7.190275e-03  8.710337e-03  1.164364e-02

In [50]:
data.values[0] # access a row

array([4.23967000e+05, 3.83325210e+07, 1.10602431e-02])

In [51]:
data['area'] # access a column

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [53]:
data

area       pop   density
California  423967  38332521  0.011060
Texas       695662  26448193  0.026303
New York    141297  19651127  0.007190
Florida     170312  19552860  0.008710
Illinois    149995  12882135  0.011644

In [52]:
data.iloc[:3,:2] # 3-1=2 in row and 2-1=1 in column

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [57]:
data.loc[:'New York',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [60]:
data

area       pop   density
California  423967  38332521  0.011060
Texas       695662  26448193  0.026303
New York    141297  19651127  0.007190
Florida     170312  19552860  0.008710
Illinois    149995  12882135  0.011644

In [66]:
data.loc[(data['area'] > 400000 ), ['area', 'density']]

area   density
California  423967  0.011060
Texas       695662  0.026303

In [67]:
# condition is masking and [[]] is fancy indexing

## Additional indexing conventions

In [68]:
data

area       pop   density
California  423967  38332521  0.011060
Texas       695662  26448193  0.026303
New York    141297  19651127  0.007190
Florida     170312  19552860  0.008710
Illinois    149995  12882135  0.011644

In [69]:
data['Texas':'New York']

area       pop   density
Texas     695662  26448193  0.026303
New York  141297  19651127  0.007190

In [71]:
# Slices can also refer to rows by number rather than by index

In [70]:
data[1:3]

area       pop   density
Texas     695662  26448193  0.026303
New York  141297  19651127  0.007190

# <font color='blue'>Operating on Data in Pandas

## Ufuncs: Index Preservation

In [72]:
import pandas as pd

In [73]:
import numpy as np

In [78]:
rng = np.random.RandomState(42)

In [75]:
rng

RandomState(MT19937) at 0x159F1440840

In [76]:
ser = pd.Series(rng.randint(0,10,4))

In [77]:
ser

0    6
1    3
2    7
3    4
dtype: int32

In [79]:
df = pd.DataFrame(rng.randint(0,10,(3,4)), columns = ['A','B','C','D'])

In [80]:
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [81]:
np.exp(ser) # exponent

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

## UFuncs: Index Alignment

In [82]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127}, name='population')

In [83]:
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [84]:
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [85]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [86]:
# union

In [87]:
area.index | population.index

C:\Users\91701\AppData\Local\Temp\ipykernel_7632\3572280633.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [88]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])

In [89]:
A

0    2
1    4
2    6
dtype: int64

In [90]:
B = pd.Series([1, 3, 5], index=[1, 2, 3])

In [91]:
B

1    1
2    3
3    5
dtype: int64

In [92]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [93]:
A.add(B)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [94]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

## Index alignment in DataFrame

In [95]:
A = pd.DataFrame(rng.randint(0,20,(2,2)), columns = list('AB'))

In [96]:
A

A   B
0  1  11
1  5   1

In [98]:
B = pd.DataFrame(rng.randint(0,10,(3,3)), columns = list('BAC'))

In [99]:
B

B  A  C
0  3  8  2
1  4  2  6
2  4  8  6

In [100]:
A + B

A     B   C
0  9.0  14.0 NaN
1  7.0   5.0 NaN
2  NaN   NaN NaN