# Creating(arange,ones,zeros,empty,axis,linspace,1D,2D), Indexing(row,column), Slicing

# <font color="red">Creating

In [12]:
# Array creation

In [2]:
import numpy as np

In [3]:
x = [1,2,3,4]

In [4]:
x

[1, 2, 3, 4]

In [5]:
type(x)

list

In [9]:
a = np.array(x)

In [10]:
a

array([1, 2, 3, 4])

In [11]:
type(a)

numpy.ndarray

## 1-D Arrays

In [15]:
x = np.array([1,2,3,4])

In [16]:
x

array([1, 2, 3, 4])

In [17]:
x.ndim

1

## 2-D Arrays

In [19]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [20]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
x.ndim

2

In [22]:
# 3-D arrays

In [26]:
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

In [27]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [28]:
x.ndim

3

In [29]:
# Higher Dimensional Arrays

In [31]:
x = np.array([1,2,3,4], ndmin=5)

In [32]:
x

array([[[[[1, 2, 3, 4]]]]])

In [33]:
x.ndim

5

## numpy.arange()

In [36]:
np.arange(3)

array([0, 1, 2])

In [37]:
np.arange(3,7)

array([3, 4, 5, 6])

In [38]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## numpy.zeros() 

In [41]:
np.zeros(2, dtype='int')

array([0, 0])

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.zeros([5,5],dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## numpy.ones()

In [70]:
np.ones(3)

array([1., 1., 1.])

In [71]:
np.ones(3, dtype = 'int')

array([1, 1, 1])

In [72]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
np.ones([2,2],dtype='int')

array([[1, 1],
       [1, 1]])

In [74]:
x.ndim

2

In [75]:
x.size

25

In [76]:
x.itemsize

8

In [77]:
x.nbytes

200

In [78]:
8 * 25

200

## numpy.empty()

In [49]:
np.empty(2)

array([0., 0.])

In [50]:
np.empty(2,dtype = 'int')

array([0, 0])

In [51]:
np.empty([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.empty([3,3], dtype = int)

array([[4151192956528754769, 4155696556156125272, 4146689356901384305],
       [4155696556156125272, 4160889769476436884, 4153135133868058276],
       [4146689356901384305, 4153135133868058276, 4149419664175477595]])

In [88]:
x = np.empty((3,3)) #tuple

In [89]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [90]:
x = np.empty([3,3]) # list

In [91]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## linspace

In [56]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [58]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## numpy.eye()

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Axis

In [129]:
x

array([[3, 5, 4, 4, 2],
       [8, 5, 7, 3, 8],
       [3, 4, 5, 4, 9],
       [6, 9, 6, 2, 4]])

In [130]:
x.max()

9

In [131]:
x.min()

2

In [135]:
x.min(axis = 0) # In each column, min value is returned

array([3, 4, 4, 2, 2])

In [134]:
x.min(axis = 1) # In each column, min value is returned

array([2, 3, 3, 2])

In [136]:
x.max(axis = 0) #  In each column, max value is returned

array([8, 9, 7, 4, 9])

## shape

In [61]:
x

array([1, 2, 3, 4])

In [62]:
x.shape

(4,)

In [63]:
x = np.array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
x.shape

(5, 5)

In [69]:
x.dtype

dtype('float64')

## reshape

In [79]:
x = np.arange(20)

In [80]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [81]:
x.ndim

1

In [83]:
x.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
x.ndim

1

In [85]:
x.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## full in numpy

In [86]:
x = np.full((3,3),fill_value=10)

In [87]:
x

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# <font color="red">Indexing(row,column)

In [92]:
# Access Array Elements

In [93]:
x = np.array([1,2,3,4])

In [94]:
x

array([1, 2, 3, 4])

In [95]:
x[0]

1

In [96]:
x[2]

3

In [97]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [98]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [100]:
x[0,1] # 2nd element on 1st row

2

In [101]:
x = np.random.randint(10,size = (4,5))

In [102]:
x

array([[3, 5, 4, 4, 2],
       [8, 5, 7, 3, 8],
       [3, 4, 5, 4, 9],
       [6, 9, 6, 2, 4]])

In [103]:
x[0]

array([3, 5, 4, 4, 2])

In [104]:
x[1]

array([8, 5, 7, 3, 8])

In [105]:
x[0][0]

3

In [106]:
x[2][2]

5

## <font color="red">Slicing

In [107]:
x

array([[3, 5, 4, 4, 2],
       [8, 5, 7, 3, 8],
       [3, 4, 5, 4, 9],
       [6, 9, 6, 2, 4]])

In [108]:
x[:]

array([[3, 5, 4, 4, 2],
       [8, 5, 7, 3, 8],
       [3, 4, 5, 4, 9],
       [6, 9, 6, 2, 4]])

In [109]:
x[0:]

array([[3, 5, 4, 4, 2],
       [8, 5, 7, 3, 8],
       [3, 4, 5, 4, 9],
       [6, 9, 6, 2, 4]])

In [115]:
# Always before comma is row and after comma is column

In [110]:
# To get 5,7,4,5

In [114]:
x[1:3,1:3] 

array([[5, 7],
       [4, 5]])

In [116]:
# To get 3,8

In [117]:
x[1:2,3:]

array([[3, 8]])

In [128]:
#x[row_starting:row_ending-1 , colum_start:colum_end-1]