# Array Manipulation(hstack,vstack,block,concatenate,append,empty_like),Datatypes,
# Comparison and Logical Operators, Copy vs View

# <font color="red">Array Manipulation

## hstack

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3])

In [5]:
y = np.array([4,5,6])

In [6]:
np.hstack((x,y)) # # it accepts only in tuple

array([1, 2, 3, 4, 5, 6])

In [7]:
x.ndim

1

In [8]:
x1 = np.array([[1,2,3],[4,5,6]])

In [9]:
y1 = np.array([[1,2,3],[4,5,6]])

In [10]:
np.hstack((x1,y1)) # it is horizontally combine the matrix(row-wise)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [11]:
np.stack((x,y)) # this is normal stack

array([[1, 2, 3],
       [4, 5, 6]])

## vstack

In [16]:
x = np.random.randint(5, size = (5,5))

In [17]:
x

array([[2, 4, 4, 0, 3],
       [3, 1, 1, 0, 1],
       [4, 1, 0, 2, 4],
       [4, 1, 1, 0, 2],
       [3, 2, 1, 2, 3]])

In [18]:
y = np.random.randint(5, size = (5,5))

In [19]:
y

array([[0, 3, 1, 0, 2],
       [3, 2, 2, 4, 0],
       [2, 4, 0, 3, 3],
       [2, 3, 2, 3, 0],
       [2, 0, 4, 2, 3]])

In [20]:
np.vstack((x,y))

array([[2, 4, 4, 0, 3],
       [3, 1, 1, 0, 1],
       [4, 1, 0, 2, 4],
       [4, 1, 1, 0, 2],
       [3, 2, 1, 2, 3],
       [0, 3, 1, 0, 2],
       [3, 2, 2, 4, 0],
       [2, 4, 0, 3, 3],
       [2, 3, 2, 3, 0],
       [2, 0, 4, 2, 3]])

## block

In [22]:
a=np.array([1,2,3])

In [23]:
b=np.array([1,2,3])

In [24]:
c=np.array([1,2,3])

In [25]:
np.block([a,b,c]) # this is also same as stack

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
a=np.random.randint(20,size=(3,3))

In [27]:
a

array([[ 4, 11, 18],
       [15,  8, 11],
       [ 4, 11, 10]])

In [28]:
b=np.random.randint(20,size=(3,3))

In [29]:
b

array([[19,  0,  9],
       [ 2, 13,  7],
       [ 9,  6, 19]])

In [32]:
np.block([a,b])

array([[ 4, 11, 18, 19,  0,  9],
       [15,  8, 11,  2, 13,  7],
       [ 4, 11, 10,  9,  6, 19]])

## concatenate

In [33]:
a

array([[ 4, 11, 18],
       [15,  8, 11],
       [ 4, 11, 10]])

In [34]:
b

array([[19,  0,  9],
       [ 2, 13,  7],
       [ 9,  6, 19]])

In [35]:
np.hstack((a,b))

array([[ 4, 11, 18, 19,  0,  9],
       [15,  8, 11,  2, 13,  7],
       [ 4, 11, 10,  9,  6, 19]])

In [36]:
np.vstack((a,b))

array([[ 4, 11, 18],
       [15,  8, 11],
       [ 4, 11, 10],
       [19,  0,  9],
       [ 2, 13,  7],
       [ 9,  6, 19]])

In [37]:
np.concatenate((a,b)) # it is defaultly column-wise

array([[ 4, 11, 18],
       [15,  8, 11],
       [ 4, 11, 10],
       [19,  0,  9],
       [ 2, 13,  7],
       [ 9,  6, 19]])

In [38]:
np.concatenate((a, b), axis=0) # axis = 0 means column-wise

array([[ 4, 11, 18],
       [15,  8, 11],
       [ 4, 11, 10],
       [19,  0,  9],
       [ 2, 13,  7],
       [ 9,  6, 19]])

In [39]:
np.concatenate((a, b), axis=1) # axis = 1 means row-wise

array([[ 4, 11, 18, 19,  0,  9],
       [15,  8, 11,  2, 13,  7],
       [ 4, 11, 10,  9,  6, 19]])

## empty_like

In [40]:
x = np.random.randint(100, size = 10)

In [41]:
x

array([84,  7, 49, 92, 11, 52, 25, 44, 42, 59])

In [42]:
y = np.empty_like(x)

In [43]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## append

In [46]:
x

array([84,  7, 49, 92, 11, 52, 25, 44, 42, 59])

In [48]:
np.append(x,100)

array([ 84,   7,  49,  92,  11,  52,  25,  44,  42,  59, 100])

In [51]:
x1 = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

In [52]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.append(x1,[[10,11,12]],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
x=np.arange(12).reshape(2,6)

In [57]:
y=np.random.randint(10,size=(3,6)) # same 6 columns is must. if not means, it shows error

In [58]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
y

array([[7, 4, 7, 6, 9, 2],
       [1, 0, 7, 6, 2, 6],
       [7, 9, 1, 6, 7, 6]])

In [60]:
np.append(x,y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  7,  4,  7,  6,  9,
        2,  1,  0,  7,  6,  2,  6,  7,  9,  1,  6,  7,  6])

In [61]:
np.append(x,y,axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 7,  4,  7,  6,  9,  2],
       [ 1,  0,  7,  6,  2,  6],
       [ 7,  9,  1,  6,  7,  6]])

# <font color="red"> Datatypes

In [65]:
x = np.array([1,2,3,4])

In [66]:
x

array([1, 2, 3, 4])

In [67]:
x.dtype

dtype('int64')

In [68]:
x = np.array(["apple","orange","mango"])

In [69]:
x.dtype

dtype('<U6')

In [70]:
x = np.array([1, 2, 3, 4], dtype='i4')

In [71]:
x

array([1, 2, 3, 4], dtype=int32)

In [72]:
x.dtype

dtype('int32')

In [73]:
x = np.array([1.1, 2.1, 3.1])

In [74]:
x

array([1.1, 2.1, 3.1])

In [75]:
x.astype('i')

array([1, 2, 3], dtype=int32)

In [76]:
x.dtype # but it remains the same

dtype('float64')

In [77]:
y = x.astype('i')

In [78]:
y

array([1, 2, 3], dtype=int32)

In [79]:
y.dtype

dtype('int32')

# <font color="red">Comparison and Logical Operators

## Comparison Operations

In [81]:
x = np.random.randint(12,size=(3,4))

In [82]:
x

array([[ 3,  2,  9,  5],
       [10,  2,  9,  2],
       [11,  0,  8,  8]])

In [83]:
y = np.random.randint(12,size=(3,4))

In [84]:
y

array([[ 8,  6,  9,  9],
       [ 1,  2, 10,  0],
       [ 5, 11, 11,  6]])

In [85]:
np.less(x,y) # x < y

array([[ True,  True, False,  True],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [86]:
np.greater(x,y) # x > y

array([[False, False, False, False],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [87]:
np.less_equal(x,y) # x <= y

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False]])

In [88]:
np.greater_equal(x,y) # x >= y

array([[False, False,  True, False],
       [ True,  True, False,  True],
       [ True, False, False,  True]])

In [89]:
np.equal(x,y) # x == y

array([[False, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [90]:
np.not_equal(x,y) # x != y

array([[ True,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

## Logical Operations

In [91]:
x = np.array([True,False,True])

In [92]:
y = np.array([False,False,True])

In [93]:
x

array([ True, False,  True])

In [94]:
y

array([False, False,  True])

In [95]:
np.logical_and(x,y)

array([False, False,  True])

In [96]:
np.logical_or(x,y)

array([ True, False,  True])

In [97]:
np.logical_not(x,y)

array([False,  True, False])

In [98]:
x

array([ True, False,  True])

In [99]:
y

array([False,  True, False])

In [101]:
np.logical_not(x)

array([False,  True, False])

In [102]:
np.logical_not(y)

array([ True, False,  True])

In [103]:
np.logical_xor(x,y)

array([ True,  True,  True])

# <font color="red"> Copy vs View

## copy

In [104]:
x = np.array([1, 2, 3, 4, 5])

In [105]:
x

array([1, 2, 3, 4, 5])

In [106]:
y = x.copy()

In [107]:
y

array([1, 2, 3, 4, 5])

In [108]:
id(x)

140560644288400

In [109]:
id(y)

140560062563120

In [110]:
y[1] = 1

In [111]:
y

array([1, 1, 3, 4, 5])

In [112]:
x

array([1, 2, 3, 4, 5])

## view

In [113]:
x

array([1, 2, 3, 4, 5])

In [114]:
y = x.view()

In [115]:
y

array([1, 2, 3, 4, 5])

In [116]:
id(x)

140560644288400

In [117]:
id(y)

140560062132656

In [118]:
y[1] = 1

In [119]:
y

array([1, 1, 3, 4, 5])

In [120]:
x

array([1, 1, 3, 4, 5])

In [121]:
# see this one affects the original also

## Check if Array Owns its Data

In [122]:
arr = np.array([1, 2, 3, 4, 5])

In [123]:
arr

array([1, 2, 3, 4, 5])

In [124]:
x = arr.copy()
y = arr.view()

In [127]:
x.base

In [128]:
y.base

array([1, 2, 3, 4, 5])

In [129]:
# The copy returns None.
# The view returns the original array.